### ISSUE TITLE
ValueError: Duplicated timeseries in CollectorRegistry - when using top_hits aggregations

### ISSUE THREAD

**Issue by ntavares** [braedon/prometheus-es-exporter#36] opened 2019-03-25 14:16 UTC
Hi @braedon 

I'm trying to set up a query with aggregations, and I'm hitting this (periodic) exception:
```
[2019-03-25 13:56:29,145] root.ERROR MainThread Error while running scheduled job.
Traceback (most recent call last):
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 210, in scheduled_run
    func()
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 121, in run_query
    update_gauges(metrics)
  File "/usr/src/app/prometheus_es_exporter/__init__.py", line 78, in update_gauges
    gauge = Gauge(metric_name, '', label_keys)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/metrics.py", line 320, in __init__
    labelvalues=labelvalues,
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/metrics.py", line 103, in __init__
    registry.register(self)
  File "/usr/local/lib/python3.6/site-packages/prometheus_client/registry.py", line 29, in register
    duplicates))
ValueError: Duplicated timeseries in CollectorRegistry: {'es_query_all_non_kubesystem_messages_by_containername_tops_hits_hits'}
```

First of all: I didn't check the code at all, nor attempted to debug it. I think the exception is harmless as I'm getting all other fields. What I think it happens is because of the result having:
```
  "aggregations": {
    "by_namespace": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 45,
      "buckets": [
// ...
        {
          "key": "some-container-name",
          "doc_count": 24,
          "tops": {
            "hits": {
              "total": 24,
              "max_score": 1.4e-45,
              "hits": [
                {
```
the last block will be repeated by each bucket, and since the metric name is forged from the aggregation name, then it will collide. I'm not very experienced with ElasticSearch either, but this is the query I'm running:
```
    QueryJson = {
        "query": {
          "bool": {
            "must_not": { "match": {"kubernetes.namespace_name": "kube-system" }},
            "filter": {
              "bool": {
                "must": [
                  { "range": { "@timestamp": { "gte": "now-1m", "lt": "now" } } }
                ]
              }
            }
          }
        },
        "aggs": {
          "by_containername": {
            "terms": {
              "field": "kubernetes.container_name.keyword"
            },
            "aggs": {
              "tops": {
                "top_hits": {
                  "size": 10
                }
              }
            }
          }
        }
      }
```
... and the goal is to have the top 10 containers with the most logging lines. If I remove the "tops" section, then I'll get all the counters for all containers, which is a bit too much. I'm not sure how to fix this at the ElasticSearch level, and it's possible that the schema of the results changed - or that people are not using aggregations at all? - do you think there's room for a fix? (I'm guessing the es-exporter will soon be on my result list for that query, with all the logging from the exceptions eheheh)

**Comment by r4j4h** [comment] 2019-09-17 18:14
Yay I'm not alone, another case reported in #30

**Comment by braedon** [comment] 2019-09-18 16:38
@ntavares Apologies for not getting back to you (much) earlier. I thought I had, but apparently not!

As best I can tell, the issue is essentially that the `top_hits` aggregation isn't explicitly supported currently, and the existing metric extraction logic isn't producing valid metrics for the results it returns.

The good news is I think this exception will have been fixed by the fix for https://github.com/braedon/prometheus-es-exporter/issues/42 - released in [0.5.2](https://github.com/braedon/prometheus-es-exporter/releases/tag/0.5.2). Please give it a try, and let me know if not!

The bad news is that this fix essentially skips the `hits` list in the `top_hits` response (as a list isn't a valid metric value). Not particularly helpful if you're wanting to get some metrics from it...

I originally was going to add support for `top_hits`, but then realised I'm not sure how it _should_ work, as `top_hits` is pretty different to the other supported aggregations - it returns documents, not metrics about documents. It's probably here where I got stuck and didn't reply... My bad!

As such, could you explain your use case here a bit more? If I understand you correctly, your indexed documents are structured logs, which you're grouping by container name with a `terms` aggregation. You're then using `top_hits` to get the top log documents for each container. Are you trying to get metrics from values in those log documents directly?

You mention removing `top_hits` will give you counters for all containers. However, if you're referring to the document counters from the `terms` buckets - the number of buckets (and therefore number of containers covered) is controlled by the `size` parameter of the `terms` aggregation. i.e. if all you're after is the number of logs from the top N containers, you can get that with just a `terms` aggregation with `size` set to N.

**Comment by braedon** [comment] 2019-09-18 16:50
Hi @r4j4h, sorry to hear you're still having issues. Your case is probably a little different, since you're not using `top_hits`, so lets jump back to https://github.com/braedon/prometheus-es-exporter/issues/30

**Comment by ntavares** [comment] 2019-09-18 21:37
Hi @braedon no worries about the delay.

I think an explicit use case can help indeed (sorry!). What I'm trying to do is to get the "top 10" containers (from all namespaces but "kube-system") that are producing the biggest amount of logs. The equivalent Timelion expression is:
```.es(split=kubernetes.container_name.keyword:10,q='!(kubernetes.namespace_name:"kube-system")')```

I just tried your suggestion and it seems to do what I want indeed! I'm not sure if I missed the ```size``` parameter completely, or if I misunderstood its function. Thanks a lot for the suggestion. You might want to add this issue as a known limitation, though, and close the issue :-)

**Comment by braedon** [comment] 2019-09-25 01:45
Good to hear you have it working @ntavares. I've added a list of unsupported aggregations to the README.

**Closed by braedon** 2019-09-25 01:45 UTC
