### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by kamalveer** [braedon/prometheus-es-exporter#56] opened 2019-12-26 10:55 UTC
### Hey! Please refer below logs, which are being created on deploying the pod and not accessible through curl. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 238, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ffb7b0f6198>: Failed to establish a new connection: [Errno 111] Connection refused
[2019-12-26 06:26:54,300] elasticsearch.WARNING MainThread GET http://ingest-node-elk-final-lb.t004-u000005:9200/_cluster/health?level=indices [status:N/A request:0.002s]

### **On executing the curl this is the error, please refer and suggest:**

url -v -g http://[fd74:ca9b:172:21::17:6032]:9206
* About to connect() to fd74:ca9b:172:21::17:6032 port 9206 (#0)
*   Trying fd74:ca9b:172:21::17:6032...
* Connection refused
* Failed connect to fd74:ca9b:172:21::17:6032:9206; Connection refused
* Closing connection 0
curl: (7) Failed connect to fd74:ca9b:172:21::17:6032:9206; Connection refused
[root@uhn7kbrc1rbrm001 ~]# 
[root@uhn7kbrc1rbrm001 ~]# 
[root@uhn7kbrc1rbrm001 ~]# 
[root@uhn7kbrc1rbrm001 ~]# curl -v -g http://[fd74:ca9b:172:19::d58d]:9206
* About to connect() to fd74:ca9b:172:19::d58d port 9206 (#0)
*   Trying fd74:ca9b:172:19::d58d...
* Connection refused
* Failed connect to fd74:ca9b:172:19::d58d:9206; Connection refused
* Closing connection 0
curl: (7) Failed connect to fd74:ca9b:172:19::d58d:9206; Connection refused

**Comment by braedon** [comment] 2020-01-05 09:58
Hi @kamalveer, that looks like a networking issues, rather than an issue with the exporter itself. The exporter can't connect to your ES cluster, and your `curl` command can't connect to the exporter.

It doesn't look like there's much I can do to help - I'd recommend digging into your network setup and making sure the exporter can connect to the ES cluster first.

**Comment by kamalveer** [comment] 2020-01-06 08:21
Thanks braedon,
I think ipv6 is the cause. Do i need to bind with ipv6 netwrok interface like we do in java --build 0.0.0.0 How can it be done in python?  or is it already there in your code? I'm not a python guy actually

**Comment by braedon** [comment] 2020-01-06 10:05
Hmm, it's possible ipv6 is the issue... I don't have a ipv6 network to test on unfortunately. I don't know of any special setup required to get python running with ipv6 (and a quick Google doesn't show anything general), but I might be missing something.

However, I'm using the [Prometheus Python client](https://github.com/prometheus/client_python) inbuilt server to serve the metrics endpoint, and it looks like that might bind to the ipv4 interface.

I don't think that explains why the exporter can't connect out to your Elasticsearch cluster, however...

Are you running on Kubernetes? Is it running ipv6 only? Or dual stack?

**Comment by kamalveer** [comment] 2020-01-06 13:37
Yes, It is k8s and only on ipv6 not dual-stack

**Comment by braedon** [comment] 2020-01-07 07:51
OK, looks like we might need to play around with the server (maybe swap it out?) to get it to support ipv6. I don't have time to work on that right away, but maybe next week? If so, would you be able to test a branch for me?

I'm still not sure why the Python Elasticsearch client can't connect to your cluster. Can you try exec-ing into the exporter pod, and curling http://ingest-node-elk-final-lb.t004-u000005:9200/_cluster/health?level=indices or similar? I want to make sure something else isn't going on before digging further into that. Thanks!

**Comment by kamalveer** [comment] 2020-01-07 08:46
Sure @braedon, I would be available for that, np.

**Comment by braedon** [comment] 2020-02-09 23:41
@kamalveer - it's been a bit more than a week, sorry, but I think I've gotten the exporter serving metrics on IPv6 in this PR: https://github.com/braedon/prometheus-es-exporter/pull/59

I've released a test version as `0.8.0a1`, so if you could give it a try and let me know how it goes, that'd be great!

**Comment by braedon** [comment] 2020-03-26 08:40
Hi @kamalveer, any chance you've been able to test this?

**Comment by braedon** [comment] 2021-04-10 09:37
Closing since it's been over a year. If anyone else runs into this issue, please leave a comment and I can look into it again.

**Closed by braedon** 2021-04-10 09:37 UTC
Labels: bug

**Comment by Shivanshugour** [comment] 2023-06-07 06:24
Hey @braedon  Can you help me with this error. I am stuck here and cant find the solution. I am a beginner in this.

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f212d175c40>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib64/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/venv/lib64/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='gb03prod2-alertmanager-k8s.saas-p.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f212d175c40>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/deploy/app/checks/ping.py", line 98, in ping
    response = requests.request(config.get('http_method','GET'),
  File "/opt/venv/lib64/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/venv/lib64/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='gb03prod2-alertmanager-k8s.saas-p.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f212d175c40>: Failed to establish a new connection: [Errno 111] Connection refused'))

Any help would be great
